Loading Python libraries

this is a test

In [4]:
#comments
import pandas as pd;
import numpy as np;
from scipy import stats;
#pd.DataFrame()

Start wih a string

In [2]:
classname = 'BitTiger_BA_501_1803_PythonBasics'
classname

'BitTiger_BA_501_1803_PythonBasics'

In [3]:
len(classname)

33

In [4]:
weeknumber = 3
classname + '_' + weeknumber

TypeError: must be str, not int

In [8]:
#weeknumber = str(weeknumber);
weeknumber = '3'
classname + '_' + weeknumber
type(classname)
weeknumber = 3
type(weeknumber)

int

In [9]:
classname.lower()
classname.upper()

'BITTIGER_BA_501_1803_PYTHONBASICS'

In [10]:
classname.replace('PythonBasics', 'PythonIntermediate')

'BitTiger_BA_501_1803_PythonIntermediate'

In [17]:
classname.find('BA')

9

In [19]:
#classname[:classname.find('BA')+2]
classname[classname.find('BA'):classname.find('BA')+2]

'BA'

Now let's add a if/else condition

In [20]:
cc = "4175004175004172";

if (cc[0:2] == '34') and (len(cc) == 15):
    print("AMEX")
if (cc[0:1] == '4') and (len(cc) == 16):
    if (cc[0:6] == '417500'):
        print("VISAELECTRON")
    else: 
        print("VISA")

VISAELECTRON


Let's play with a string list

In [22]:
colors = ['red', 'blue','green']

how indexing works: Python index starts with 0

In [28]:
print(colors[0]);
print(colors[1]);
print(colors[2]);
print(len(colors));
print(colors[(len(colors)-1)]);

red
blue
green
3
green


list manipulations

In [29]:
colors.append('black');
print(colors);

['red', 'blue', 'green', 'black']


In [30]:
colors.insert(0, 'orange');
print(colors)

['orange', 'red', 'blue', 'green', 'black']


In [31]:
colors.sort();
print(colors)

['black', 'blue', 'green', 'orange', 'red']


Numpy array

In [ ]:
list cannot have this operation

In [32]:
y = [1,2,3]

In [33]:
print(y/3)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [35]:
x = np.array([1,2,3]);
x/3

array([0.33333333, 0.66666667, 1.        ])

In [36]:
x.shape

(3,)

In [ ]:
2-D array (similar to matrix in R)

In [37]:
x2 = np.array([[1,2,3], [4, 5, 6]]);
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
x2.shape

(2, 3)

In [39]:
x.dtype

dtype('int32')

In [187]:
x[0]

1

pandas data frame

In [40]:
df = pd.DataFrame(
{"a" : [4,5,6],
 "b" : [7,8,9],
 "c" : [10,11,12]
}
);
df

a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

In [189]:
df.shape

(3, 3)

In [206]:
df.describe()

a    b     c
count  3.0  3.0   3.0
mean   5.0  8.0  11.0
std    1.0  1.0   1.0
min    4.0  7.0  10.0
25%    4.5  7.5  10.5
50%    5.0  8.0  11.0
75%    5.5  8.5  11.5
max    6.0  9.0  12.0

In [43]:
#df
df[['a']]

a
0  4
1  5
2  6

In [42]:
df['a']

0    4
1    5
2    6
Name: a, dtype: int64

In [46]:
df[0:2]

a  b   c
0  4  7  10
1  5  8  11

In [47]:
#df$a (R)
#df.a (Python)
df[df.a == 4]

a  b   c
0  4  7  10

In [48]:
df.drop('a',1)  #1 for column, 0 for row

b   c
0  7  10
1  8  11
2  9  12

In [53]:
df.drop(0, 0) #0 for row

a  b   c   d
1  5  8  11  11
2  6  9  12  12

In [51]:
df['d'] = [10,11,12];
df

a  b   c   d
0  4  7  10  10
1  5  8  11  11
2  6  9  12  12

aggregation

In [88]:
df = pd.DataFrame(
{"a" : [4,5,6],
"b" : [7,8,9],
"color" : ["red", "red", "blue"]
});
df

a  b color
0  4  7   red
1  5  8   red
2  6  9  blue

In [90]:
agg = df.groupby('color').sum()

#SELECT COLOR, SUM(a) AS a, SUM(b) AS b FROM df GROUP BY COLOR

In [91]:
pd.merge(df, agg, how = "left", on = "color")

a_x  b_x color  a_y  b_y
0    4    7   red    9   15
1    5    8   red    9   15
2    6    9  blue    6    9

merge (SQL JOIN)

In [87]:
df.groupby(['color']).mean()

KeyError: 'color'

In [57]:
df1 = pd.DataFrame(
{"a" : [4,5,6],
"b" : [7,8,9],
"color" : ["red", "yellow", "blue"]
});

df2 = pd.DataFrame(
{"a" : [1,2,3],
"b" : [7,6,7],
"color" : ["red", "yellow", "green"]
});

In [58]:
pd.merge(df1, df2, how = 'inner', on = 'color')

a_x  b_x   color  a_y  b_y
0    4    7     red    1    7
1    5    8  yellow    2    6

In [59]:
pd.merge(df1, df2, how = 'left', on = 'color')

a_x  b_x   color  a_y  b_y
0    4    7     red  1.0  7.0
1    5    8  yellow  2.0  6.0
2    6    9    blue  NaN  NaN

In [60]:
pd.merge(df1, df2, how = 'right', on = 'color')

a_x  b_x   color  a_y  b_y
0  4.0  7.0     red    1    7
1  5.0  8.0  yellow    2    6
2  NaN  NaN   green    3    7

In [61]:
pd.merge(df1, df2, how = 'outer', on = 'color')

a_x  b_x   color  a_y  b_y
0  4.0  7.0     red  1.0  7.0
1  5.0  8.0  yellow  2.0  6.0
2  6.0  9.0    blue  NaN  NaN
3  NaN  NaN   green  3.0  7.0

remove duplicates from list/scalar

In [73]:
l = [1, 2, 3, 1, 2, 5, 6, 7, 8]

In [74]:
set(l)
#unique(l)

{1, 2, 3, 5, 6, 7, 8}

In [ ]:
remove duplicates from data frame

In [100]:
df = pd.DataFrame({
    "A":["black", "red", "white", "white"], 
    "B":[0,1,1,1], 
    "C":["A","B","A","A"]});
df

A  B  C
0  black  0  A
1    red  1  B
2  white  1  A
3  white  1  A

In [ ]:
R:
df$D <- ifelse(df$C == "A", "Group1", 
        ifelse(df$C == "B", "Group2", "Group3"))

In [76]:
df.drop_duplicates()

A  B  C
0  black  0  A
1    red  1  B
2  white  1  A

You are given two tables - friend_request and request_accepted. Friend_request contains 1.requester_id, 2. time and 3. request_id and request_accepted table contains 1.time, 2.acceptor_id and 3. requestor_id. How will you determine the overall acceptance rate of requests? 

In [62]:
friend_request = pd.DataFrame({
    'requester_id' : ['0001', '0002', '0003'],
    'time' : ['2018-07-06 01:23:00','2018-07-07 05:50:00', '2018-07-08 03:11:00' ],
    'request_id' : ['01ABC1', '02BDE2', 'KDDBC1']});
friend_request

requester_id                 time request_id
0         0001  2018-07-06 01:23:00     01ABC1
1         0002  2018-07-07 05:50:00     02BDE2
2         0003  2018-07-08 03:11:00     KDDBC1

In [63]:
request_accepted = pd.DataFrame({
    'requester_id' : ['0001', '0003'],
    'acceptor_id' : ['0011', '0043'],
    'time' : ['2018-07-10 01:00:00','2018-07-08 03:20:00'],
    'request_id' : ['01ABC1', 'KDDBC1']});
request_accepted

requester_id acceptor_id                 time request_id
0         0001        0011  2018-07-10 01:00:00     01ABC1
1         0003        0043  2018-07-08 03:20:00     KDDBC1

note: not all friend requests are accepted.

In [68]:
merged_table = pd.merge(friend_request, 
         request_accepted, 
         how = 'left', on = 'request_id');
merged_table

requester_id_x               time_x request_id requester_id_y acceptor_id  \
0           0001  2018-07-06 01:23:00     01ABC1           0001        0011   
1           0002  2018-07-07 05:50:00     02BDE2            NaN         NaN   
2           0003  2018-07-08 03:11:00     KDDBC1           0003        0043   

                time_y  
0  2018-07-10 01:00:00  
1                  NaN  
2  2018-07-08 03:20:00

In [252]:
merged_table.isnull().sum()

requester_id_x    0
time_x            0
request_id        0
requester_id_y    1
acceptor_id       1
time_y            1
dtype: int64

In [67]:
col = merged_table['_merge'] == 'both'
#col.sum() / col.count()
#True = 1, False = 0

col.mean()

0.6666666666666666

alternatively

In [82]:
col = merged_table['requester_id_y'].isnull();
col
#col
1- col.mean()

0.6666666666666667

In [ ]:
write a function

In [77]:
def CreditCardType(cc):
    if (cc[0:2] == '34') and (len(cc) == 15):
        card_type = "AMEX"
    if (cc[0:1] == '4') and (len(cc) == 16):
        if (cc[0:6] == '417500'):
            card_type = "VISAELECTRON"
        else: 
            card_type = "VISA"
    return(card_type)

In [78]:
CreditCardType('4175004175004172')

'VISAELECTRON'

In [79]:
CreditCardType('346416800707698')

'AMEX'

In [80]:
CreditCardType('3464')

UnboundLocalError: local variable 'card_type' referenced before assignment

Let's make the function more user friendly

In [83]:
def CreditCardTypeV2(cc):
    if (cc[0:2] == '34') and (len(cc) == 15):
        card_type = "AMEX"
    if (cc[0:1] == '4') and (len(cc) == 16):
        if (cc[0:6] == '417500'):
            card_type = "VISAELECTRON"
        else: 
            card_type = "VISA"
    else: 
        card_type = "This is not a valid card number"
    return(card_type)

In [84]:
CreditCardTypeV2('3464')

'This is not a valid card number'

Demonstrate Law of Large Numbers (LLN)

In [103]:
population_mean = (1/2)*(1+10);
population_var = (1/12)*(10-1)**2;
print(population_mean);
print(population_var);

5.5
6.75


In [107]:
d10 = np.random.uniform(1,10,10);
print(d10.mean());
print(d10.var())

5.893968054948802
5.3765975469777825


In [109]:
d100 = np.random.uniform(1,10,100);
print(d100.mean());
print(d100.var());

5.636423626242845
6.703447282366085


t test using stats library

In [92]:
outcome = np.random.normal(0,1,100);
outcome[0:10]

array([ 1.02950110e+00, -3.14635001e-02, -7.70137355e-01,  9.73008212e-01,
       -7.99729685e-01, -1.60944548e+00,  5.61014537e-01, -1.21738920e+00,
       -1.15980465e-03, -1.08736949e+00])

In [93]:
np.random.binomial(1, 1/2, 10)

array([1, 1, 1, 0, 0, 1, 0, 1, 0, 1])

In [94]:
group_label = np.array(["treatment", "control"])[np.random.binomial(1, 1/2, 100)];
group_label[0:10]

array(['treatment', 'control', 'treatment', 'treatment', 'treatment',
       'treatment', 'treatment', 'treatment', 'control', 'treatment'],
      dtype='<U9')

In [95]:
df = pd.DataFrame(
{"outcome" : outcome,
"group_label" : group_label}
);
df[:5]

outcome group_label
0  1.029501   treatment
1 -0.031464     control
2 -0.770137   treatment
3  0.973008   treatment
4 -0.799730   treatment

In [96]:
df.groupby(["group_label"]).describe()

outcome                                                   \
              count      mean       std       min       25%      50%   
group_label                                                            
control        47.0 -0.055848  0.974467 -1.953605 -0.851023 -0.00116   
treatment      53.0  0.026717  1.110483 -2.187207 -0.708362 -0.05495   

                                 
                  75%       max  
group_label                      
control      0.702630  1.923604  
treatment    0.871211  3.569757

In [98]:
control = df.loc[(df.group_label == 'control'), ['outcome']];
treatment = df.loc[df.group_label == 'treatment', 'outcome'];

the result is not surprising, 
because control and treatment are coming from 
the same population N(0,1),
the P-value = 0.40 > 0.05. so we fail to reject H0
that mean(treatment) = mean(control)

In [99]:
stats.ttest_ind(treatment,control)

Ttest_indResult(statistic=array([0.39288931]), pvalue=array([0.69525456]))

ANOVA

In [107]:
outcome1 = np.random.normal(10,100,1000);
outcome2 = np.random.normal(20,100,1000);
outcome3 = np.random.normal(30,100,1000);
# outcome should be: the means of the three groups are different

In [108]:
outcome1df = pd.DataFrame({
    'outcome' : outcome1,
    'group_label' : 'group 1'
});

In [109]:
outcome2df = pd.DataFrame({
    'outcome' : outcome2,
    'group_label' : 'group 2'
});

In [110]:
outcome3df = pd.DataFrame({
    'outcome' : outcome3,
    'group_label' : 'group 3'
});

In [111]:
df = pd.concat([outcome1df, outcome2df, outcome3df], axis = 0)
# similar to bind in r, here if axis = 0, rbind, if axis = 1, cbind

In [112]:
df.groupby(["group_label"]).describe()

outcome                                                           \
              count       mean         std         min        25%        50%   
group_label                                                                    
group 1      1000.0  10.863357   97.918958 -377.046333 -55.294361  12.796217   
group 2      1000.0  21.358972  101.110497 -284.337690 -46.311616  21.179665   
group 3      1000.0  31.620843  102.870001 -275.675478 -39.610766  32.896377   

                                     
                    75%         max  
group_label                          
group 1       74.221566  317.546881  
group 2       89.176592  365.840496  
group 3      102.239658  322.195607

because three outcomes are coming from different population mean, the P-value is small and we reject H0 that all three populations have same mean

In [113]:
stats.f_oneway(outcome1, outcome2, outcome3)
# one way ANOVA: f_oneway() function
# one-way ANOVA: 
# two-way ANOVA:
# from below result, pvalue is much smaller than 0.05 - reject H0 - diff mean

F_onewayResult(statistic=10.632751707840397, pvalue=2.5035735129241728e-05)

random sampling 10% of data

In [114]:
df.sample(frac=0.001, replace=True)
# frac=0.001 - randomly select 0.1%
# if replace=false - with replacement - bootstrap sampling

outcome group_label
411  -82.159053     group 1
395  -62.187151     group 3
506  164.462743     group 1

random sampling 5 rows

In [115]:
df.sample(n=5, replace = True)
# n=5, randomly select 5 sample points

outcome group_label
383  -20.903880     group 1
568  112.945353     group 2
823  -12.404173     group 2
186  -56.824167     group 3
785  -43.391092     group 2

random sampling 5 rows from each group

In [97]:
sample_group1 = df.loc[df.group_label == 'group 1'].sample(n=5);
sample_group2 = df.loc[df.group_label == 'group 2'].sample(n=5);
sample_group3 = df.loc[df.group_label == 'group 3'].sample(n=5);

a more advanced way is to use lambda operator to create small anonymous function 

In [116]:
#def f(x,y):
#    return(x**y);

f = lambda x, y : x ** y;
f(2,3)

8

In [117]:
def f(x,y):
    return(x**y);

f(2,3)

8

In [118]:
df.groupby('group_label').apply(lambda x: x.sample(n=5))
# within each group, randomly subset 5 samples and combine the result

outcome group_label
group_label                            
group 1     283 -127.509972     group 1
            606  151.749762     group 1
            903    6.912432     group 1
            604  -12.722751     group 1
            466   38.171356     group 1
group 2     863  139.202932     group 2
            992   73.620575     group 2
            497   18.788280     group 2
            519  -25.409195     group 2
            802  111.015188     group 2
group 3     568   -2.828338     group 3
            855    6.008299     group 3
            131  110.830672     group 3
            454   39.592844     group 3
            38    84.370644     group 3

if we have more than one sampling dimensions

In [120]:
#df.shape
df['leveltwo_group_label'] = np.array(["Red", "Blue", "Green"])[np.random.binomial(2, 1/3, 3000)]; 
df.groupby(["group_label", "leveltwo_group_label"]).describe()
#df[:5]

outcome                                     \
                                   count       mean         std         min   
group_label leveltwo_group_label                                              
group 1     Blue                   434.0  12.737410  100.987837 -377.046333   
            Green                  113.0  15.088660   91.583751 -214.729487   
            Red                    453.0   8.013912   96.577905 -332.850779   
group 2     Blue                   454.0  24.424066  103.993530 -274.505000   
            Green                  110.0  33.113610  103.694436 -284.337690   
            Red                    436.0  15.201717   97.155530 -271.188999   
group 3     Blue                   458.0  27.604829  101.721625 -245.500267   
            Green                  111.0  24.822464  103.057526 -259.323654   
            Red                    431.0  37.639299  103.951257 -275.675478   

                                                                                
                                        25%        50%         75%         max  
group_label leveltwo_group_label                                                
group 1     Blue                 -53.467163  11.341857   73.708719  317.546881  
            Green                -32.918122  10.265290   72.347515  215.645327  
            Red                  -62.990122  17.312376   74.423595  284.736888  
group 2     Blue                 -50.087390  29.914684   92.071746  365.840496  
            Green                -37.523247  42.025904  107.617515  238.075638  
            Red                  -42.737932  10.592198   82.061479  282.235844  
group 3     Blue                 -45.204654  27.640324  102.960822  303.158523  
            Green                -41.704673  25.061723   94.686809  290.986909  
            Red                  -35.868616  45.711407  103.136564  322.195607

In [121]:
df.groupby(['group_label', 'leveltwo_group_label']).apply(lambda x: x.sample(n=2))

outcome group_label  \
group_label leveltwo_group_label                               
group 1     Blue                 865  -89.485426     group 1   
                                 660  -64.601291     group 1   
            Green                106  210.439000     group 1   
                                 539    1.627619     group 1   
            Red                  113  110.849545     group 1   
                                 627  -52.285112     group 1   
group 2     Blue                 229   68.301554     group 2   
                                 974 -126.642052     group 2   
            Green                820   44.973370     group 2   
                                 188  109.269253     group 2   
            Red                  413   37.896827     group 2   
                                 169   25.491172     group 2   
group 3     Blue                 823    0.788480     group 3   
                                 31   135.130858     group 3   
            Green                583   36.903187     group 3   
                                 29   -42.675632     group 3   
            Red                  38    84.370644     group 3   
                                 320  130.675753     group 3   

                                     leveltwo_group_label  
group_label leveltwo_group_label                           
group 1     Blue                 865                 Blue  
                                 660                 Blue  
            Green                106                Green  
                                 539                Green  
            Red                  113                  Red  
                                 627                  Red  
group 2     Blue                 229                 Blue  
                                 974                 Blue  
            Green                820                Green  
                                 188                Green  
            Red                  413                  Red  
                                 169                  Red  
group 3     Blue                 823                 Blue  
                                 31                  Blue  
            Green                583                Green  
                                 29                 Green  
            Red                  38                   Red  
                                 320                  Red

In [1]:
line = "something something"
line

'something something'

In [5]:
num = float(line)

ValueError: could not convert string to float: 'something something'

In [6]:
var1 = ['cat', 'dog', 'lion', 'squirrel']
print(tuple(var1))

('cat', 'dog', 'lion', 'squirrel')


In [12]:
list1 = ['amsterdam', 'espresso','ice-cream']
list1

['amsterdam', 'espresso', 'ice-cream']

In [13]:
list2 = list1
list2

['amsterdam', 'espresso', 'ice-cream']

In [14]:
list1.remove('amsterdam')
list1

['espresso', 'ice-cream']

In [15]:
list2

['espresso', 'ice-cream']

In [16]:
rows = 3
cols = 2
def main():
    values = [['art','afternoon'],
              ['mushroom','pizza'],
              ['parma','italy']]
    for r in range(3):
        for c in range(2):
            print(r, c, values[r][c].ljust(12), end='')
        print()
main()

0 0 art         0 1 afternoon   
1 0 mushroom    1 1 pizza       
2 0 parma       2 1 italy       
